@echo off
setlocal DisableDelayedExpansion
rem Optional fallback when a browser disallows local file pages.
rem Uses built-in Windows PowerShell and a loopback TCP listener, not HttpListener.
rem No execution-policy changes, administrator privileges, or installations.
set "ROOM_EDITOR_ROOT=%~dp0"
powershell.exe -NoLogo -NoProfile -Command ^
  "$ErrorActionPreference='Stop'; $root=[IO.Path]::GetFullPath($env:ROOM_EDITOR_ROOT); $listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,8765); try {$listener.Start()} catch {Write-Host 'Cannot start localhost:8765. Close another editor server and retry.'; exit 1}; Write-Host 'Ember Hollow room editor: http://localhost:8765'; Write-Host 'Keep this window open. Press Ctrl+C to stop.'; Start-Process 'http://localhost:8765'; try {while($true) {if(-not $listener.Pending()){Start-Sleep -Milliseconds 100; continue}; $client=$listener.AcceptTcpClient(); try {$client.ReceiveTimeout=3000; $client.SendTimeout=3000; $stream=$client.GetStream(); $reader=[IO.StreamReader]::new($stream); $line=$reader.ReadLine(); if(-not $line){continue}; $parts=$line.Split(' '); $method=$parts[0]; $target=$parts[1].Split('?')[0]; $relative=[Uri]::UnescapeDataString($target).TrimStart('/'); if(-not $relative){$relative='index.html'}; $file=[IO.Path]::GetFullPath([IO.Path]::Combine($root,$relative.Replace('/',[IO.Path]::DirectorySeparatorChar))); $status='200 OK'; $type='application/octet-stream'; if(($method -ne 'GET') -and ($method -ne 'HEAD')) {$status='405 Method Not Allowed'; $body=[Text.Encoding]::UTF8.GetBytes('GET or HEAD required')} elseif((-not $file.StartsWith($root,[StringComparison]::OrdinalIgnoreCase)) -or (-not [IO.File]::Exists($file))) {$status='404 Not Found'; $body=[Text.Encoding]::UTF8.GetBytes('Not found')} else {$types=@{'.html'='text/html; charset=utf-8';'.js'='text/javascript; charset=utf-8';'.css'='text/css; charset=utf-8';'.json'='application/json; charset=utf-8';'.svg'='image/svg+xml';'.png'='image/png'}; $ext=[IO.Path]::GetExtension($file).ToLowerInvariant(); if($types.ContainsKey($ext)){$type=$types[$ext]}; $body=[IO.File]::ReadAllBytes($file)}; $header=[Text.Encoding]::ASCII.GetBytes(('HTTP/1.1 '+$status+[char]13+[char]10+'Content-Type: '+$type+[char]13+[char]10+'Content-Length: '+$body.Length+[char]13+[char]10+'Cache-Control: no-store'+[char]13+[char]10+'Connection: close'+[char]13+[char]10+[char]13+[char]10)); $stream.Write($header,0,$header.Length); if($method -ne 'HEAD'){$stream.Write($body,0,$body.Length)}; $stream.Flush()} catch {Write-Host ('Request skipped: '+$_.Exception.Message)} finally {$client.Close()}}} finally {$listener.Stop()}"
if errorlevel 1 pause
endlocal
